wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    code_path: code/pipeline/tabl.py
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
dataset:
  desc: null
  value: esugj36b.h5
params:
  desc: null
  value:
    batch_size:
      desc: Size of each mini-batch
      value: 32
    epochs:
      desc: Number of epochs to train over
      value: 100
yaml:
  desc: null
  value: ../yaml/tabl.yaml
