wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    code_path: code/pipeline/deeplob.py
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
dataset:
  desc: null
  value: esugj36b.h5
params:
  desc: null
  value:
    batch_size:
      desc: Size of each mini-batch
      value: 64
    dropout:
      desc: null
      value: 0.1
    epochs:
      desc: Number of epochs to train over
      value: 100
    num_features:
      desc: null
      value: 40
    number_of_lstm:
      desc: null
      value: 64
    window_length:
      desc: null
      value: 200
yaml:
  desc: null
  value: ../yaml/deeplob.yaml
