wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    code_path: code/pipeline/tabl.py
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
params:
  desc: null
  value:
    batch_size: 100
    dropout: 0.5
    learning_rate: 0.001
yaml:
  desc: null
  value: ~/ProdigyAI/yaml/tabl.yaml
